# Generated by Django 5.0.6 on 2024-07-12 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=600, verbose_name='Título')),
                ('slug', models.SlugField(max_length=650, verbose_name='Slug')),
                ('descricao', models.TextField(default='', max_length=1000, verbose_name='Descrição')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True, verbose_name='Data Publicação')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Data Alteração')),
                ('texto', models.TextField(default='', verbose_name='Texto')),
                ('visibilidade', models.BooleanField(default=True, verbose_name='Visibilidade')),
                ('foto', models.ImageField(blank=True, default=None, null=True, upload_to='posts/%Y/%m/%d')),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
