# Generated by Django 5.0.6 on 2024-07-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeImagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_qrcode', models.ImageField(upload_to='qr_code/%Y/%m/%d')),
            ],
            options={
                'verbose_name': 'QR CODE Imagem',
                'verbose_name_plural': 'CODE Imagens',
            },
        ),
    ]
