# Generated by Django 5.0.6 on 2024-07-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geradores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrcodeimagens',
            options={'verbose_name': 'QR CODE Imagem', 'verbose_name_plural': 'QR CODE Imagens'},
        ),
    ]
