# Generated by Django 5.0.6 on 2024-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geradores', '0002_alter_qrcodeimagens_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodeimagens',
            name='tipo',
            field=models.CharField(choices=[('Link', 'Link'), ('Whatsapp', 'Whatsapp'), ('Email', 'Email'), ('Sms', 'Sms'), ('Pix', 'Pix'), ('Wifi', 'Wifi')], default='Link', max_length=255, verbose_name='Tipo'),
        ),
    ]
